#!/usr/bin/env bash
# bash script install nginx

apt-get update -y
apt-get install nginx -y

mkdir /etc/nginx/html

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

sudo sed -i 's/^listen\ \[::\]:80 default\_server;/listen\ 80\ default\_server;/' /etc/nginx/sites-available/default
service nginx start
