#!/usr/bin/env bash
# bash script install nginx

apt-get update -y
apt-get install nginx -y

mkdir /etc/nginx/html

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

sudo sed -i 'listen 80 default_server;/a rewrite ^\redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default
service nginx start
sudo -e "\nCompleted.\n"
