#!/usr/bin/env bash

# Update package index
sudo apt update

# Install nginx
sudo apt install -y nginx

echo "<html><body>Hello World!</body></html>" | sudo tee /var/www/html/index.html >/dev/null


echo "<html><head><title>Redirected</title><meta http-equiv=\"refresh\" content=\"0; url=http://example.com/\" /></head><body></body></html>" | sudo tee /var/www/html/redirect_page.html >/dev/null

sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 http://\$host/redirect_page.html;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'
sudo nginx -s reload

