#!/usr/bin/env bash
Configure HAproxy so that it send traffic to web-01 and web-02

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend sthablym.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 524783-web-01 100.26.234.241:80
        server 524783-web-02 52.87.155.35:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
