#!/usr/bin/env bash
# backup and compress my databases

day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

mysqldump --defaults-extra-file=~/.my.cnf database_name > backup.sql
tar -czvf "$file_name" backup.sql
