#!/usr/bin/env bash
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command
#Displays Y U no love me?!
sigterm_handler()
{
	echo "I hate the kill command"
}

sigint_handler() 
{
	echo "Y U no love me?!"
}

sigquit_handler()
{
	echo "Deleting PID file and terminating..."
	rm -f /var/run/myscript.pid
	exit 0
}

trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'sigquit_handler' SIGQUI

echo $$ >  /var/run/myscript.pid 

while true; 
do
	echo "To infinity and beyond"
	sleep 1
done 
