#!/usr/bin/env bash
#script that loops from 1 to 10
i=1
while [ "$i" -le 8 ]
do
	if [ "$i" -eq 3 ]
	then
		echo "Best School"
		echo "bad luck"
	elif [ "$i" -eq 6 ]
	then
		echo "Best School"
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
